# Generated by Django 3.2.4 on 2021-06-15 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=25, unique=True, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25, unique=True, verbose_name='Product Name')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='movements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('location_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_from', to='management.locations')),
                ('location_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_to', to='management.locations')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.products')),
            ],
            options={
                'verbose_name': 'Movement',
                'verbose_name_plural': 'Movements',
            },
        ),
    ]
