# Generated by Django 3.2.4 on 2021-06-15 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_movements_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='location_from',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_from', to='management.locations'),
        ),
    ]
