# Generated by Django 3.2.4 on 2021-06-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_movements_location_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movements',
            name='location_from',
            field=models.CharField(max_length=25, verbose_name='Location_from'),
        ),
        migrations.AlterField(
            model_name='movements',
            name='location_to',
            field=models.CharField(max_length=25, verbose_name='Location_to'),
        ),
        migrations.AlterField(
            model_name='movements',
            name='product',
            field=models.CharField(max_length=25, verbose_name='product'),
        ),
    ]
